### ISSUE TITLE
file "/srv/locales/en-us" does not exist

### ISSUE THREAD

**Issue by SantiMA10** [manekinekko/actions-on-google-i18n#6]
I'm trying to deploy, with the local emulator works fine, a Firebase Cloud Function, but I get the following error:

```
Detailed stack trace: Error: [actions-on-google-i18n] file "/srv/locales/en-us" does not exist.
    at __i18nFactory (/srv/node_modules/@sfeir/actions-on-google-i18n/index.js:68:15)
    at I18n.use (/srv/node_modules/@sfeir/actions-on-google-i18n/index.js:100:25)
    at Object.<anonymous> (/srv/index.js:12:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

[Here is my code](https://github.com/SantiMA10/excuse-generator/tree/v2)

**Comment by manekinekko** [comment]
Try renaming your locales files to `en-us` and `es-es` (all in lowercase). And let me know.

**Comment by SantiMA10** [comment]
Thanks, it was just that, I never remember that marcOS is case insensitive 😅.

**Comment by manekinekko** [comment]
It's also because the incoming request has the user's locale in lowercase.
